export default {
	tiers : [
		{
			title: 'Free',
			id: 1,
			price: 1.5,
			name:'Sign Rathi ',
			date: '2 days ago',
			buttonText: 'Sign up for free',
			buttonVariant: 'outlined',
			size: 30,
		},
		{
			title: 'Pro',
			id: 2,
			price: 1,
			name:'Roboto',
			date: '3 days ago',
			buttonText: 'Get started',
			buttonVariant: 'contained',
			size: 27,
		},
		{
			title: 'Enterprise',
			id: 3,
			price: 1.25,
			name:'Monserat',
			date: 'May 23',
			buttonText: 'Contact us',
			buttonVariant: 'outlined',
			size: 20,
		},
		{
			title: 'Free',
			price: 3.0,
			id: 4,
			name:'Poppins',
			date: '3 days ago',
			buttonText: 'Sign up for free',
			buttonVariant: 'outlined',
			size: 16,
		},
		{
			title: 'Pro',
			id: 5,
			price: 1.5,
			name:'Times New Roman',
			date: '5 days ago',
			buttonText: 'Get started',
			buttonVariant: 'contained',
			size: 28,
		},
		{
			title: 'Enterprise',
			id: 6,
			price: 2.5,
			name:'Helvetica',
			date: 'Jan 21',
			buttonText: 'Contact us',
			buttonVariant: 'outlined',
			size: 26,
		},
	]
};